name: ASP.NET Core 8 API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: SimpleAPI/SimpleAPI.sln
      TEST_PROJECT_PATH: SimpleAPI.Test/SimpleAPI.Test.csproj

    steps:
      # Step 1: Checkout the code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 2.1: Cache NuGet packages
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore $SOLUTION_PATH

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build $SOLUTION_PATH --no-restore --configuration Release

      # Step 5: Run Unit Tests (xUnit) with diagnostic verbosity
      - name: Run unit tests
        run: dotnet test $TEST_PROJECT_PATH --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --verbosity diagnostic
      # Step 6: Upload Test Results as Artifact
      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@latest
        with:
          name: Test Results
          path: ${{ github.workspace }}/SimpleAPI.Test/bin/Release/net8.0/test_results.trx